version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
      - "9443:5443"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - ../generate-self-signed-cert:/etc/nginx/ssl
